# Generated by Django 5.2 on 2025-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_request_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего запроса'),
        ),
    ]
