# Generated by Django 5.2 on 2025-04-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_botuser_last_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.ImageField(upload_to='media/recipes_photo/', verbose_name='Фото блюда'),
        ),
    ]
