# Generated by Django 5.2 on 2025-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.ImageField(upload_to='recipes_photo/', verbose_name='Фото блюда'),
        ),
    ]
