# Generated by Django 5.2 on 2025-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='free_request_left',
        ),
        migrations.AddField(
            model_name='botuser',
            name='requests_today',
            field=models.IntegerField(default=0),
        ),
    ]
