# Generated by Django 5.2 on 2025-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_botuser_free_request_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='free_request_left',
            field=models.IntegerField(default=3, verbose_name='Осталось бесплатных запросов'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание подписки'),
        ),
    ]
